version: '3.8'

services:
    nginx:
        image: docker.io/library/nginx:1.25.2
        ports:
            - ${PORT}:443
        volumes:
            - ./ssl:/etc/ssl:ro
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        restart: always
        depends_on:
            - fastapi

    fastapi:
        build: .
        env_file:
            - .env
        volumes:
            - /var/log/fastapi-casbin:/app/Log
        restart: always
        depends_on:
            db:
                condition: service_healthy
        command: uvicorn main:app --host 0.0.0.0

    db:
        image: mongo:6.0.7
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - mongo_data:/data/db
        env_file:
            - .env
        restart: always
        healthcheck:
            test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
            start_period: 60s
            interval: 30s
            timeout: 30s
            retries: 5


volumes:
    mongo_data:
